In [2]:
%matplotlib notebook

In [32]:
import time
import numpy as np
import pandas as pd
import xarray as xr

from collections import OrderedDict
from importlib import reload

In [4]:
from plottr import plottr
reload(plottr)

<module 'plottr.plottr' from 'd:\\Dropbox\\Code\\labpyDesktop\\plottr\\plottr\\plottr.py'>

In [64]:
x = np.linspace(0, 8, 21, dtype=float)
# y = np.arange(9, dtype=float)
# xx, yy = np.meshgrid(x, y, indexing='ij')
# zz = xx + yy**2
z = np.cos(x)

# x2 = xx.reshape(-1)[:]
# y2 = yy.reshape(-1)[:]
# z2 = zz.reshape(-1)[:]
x2 = x
z2 = z

data = {
    'id' : 'Some data',
    'datasets' : {
        'z' : {
            'values' : z2.tolist(),
            'axes' : ['x', ],
        },
        'x' : {
            'values' : x2.tolist(),
        },
#         'y' : {
#             'values' : y2,
#         },
#         'w' : {
#             'values' : z2,
#         }
    }
}

In [66]:
dfs = plottr.dictToDataFrames(data['datasets'])
dfs

[z           0
 x            
 0.0  1.000000
 0.4  0.921061
 0.8  0.696707
 1.2  0.362358
 1.6 -0.029200
 2.0 -0.416147
 2.4 -0.737394
 2.8 -0.942222
 3.2 -0.998295
 3.6 -0.896758
 4.0 -0.653644
 4.4 -0.307333
 4.8  0.087499
 5.2  0.468517
 5.6  0.775566
 6.0  0.960170
 6.4  0.993185
 6.8  0.869397
 7.2  0.608351
 7.6  0.251260
 8.0 -0.145500]

In [73]:
arr0 = xr.DataArray(dfs[0]).unstack('dim_0').squeeze()
arr0

<xarray.DataArray (x: 21)>
array([ 1.      ,  0.921061,  0.696707,  0.362358, -0.0292  , -0.416147,
       -0.737394, -0.942222, -0.998295, -0.896758, -0.653644, -0.307333,
        0.087499,  0.468517,  0.775566,  0.96017 ,  0.993185,  0.869397,
        0.608351,  0.25126 , -0.1455  ])
Coordinates:
    z        int64 0
  * x        (x) float64 0.0 0.4 0.8 1.2 1.6 2.0 2.4 2.8 3.2 3.6 4.0 4.4 4.8 ...

In [81]:
for k, v in arr0.coords.items():
    if not isinstance(v.values, np.ndarray):
        arr0 = arr0.drop(k)

In [82]:
arr0

<xarray.DataArray (x: 21)>
array([ 1.      ,  0.921061,  0.696707,  0.362358, -0.0292  , -0.416147,
       -0.737394, -0.942222, -0.998295, -0.896758, -0.653644, -0.307333,
        0.087499,  0.468517,  0.775566,  0.96017 ,  0.993185,  0.869397,
        0.608351,  0.25126 , -0.1455  ])
Coordinates:
  * x        (x) float64 0.0 0.4 0.8 1.2 1.6 2.0 2.4 2.8 3.2 3.6 4.0 4.4 4.8 ...

TypeError: '<' not supported between instances of 'str' and 'int'

In [67]:
arr = plottr.dataFrameToXArray(dfs[0])
arr

<xarray.DataArray (x: 21)>
array([ 1.      ,  0.921061,  0.696707,  0.362358, -0.0292  , -0.416147,
       -0.737394, -0.942222, -0.998295, -0.896758, -0.653644, -0.307333,
        0.087499,  0.468517,  0.775566,  0.96017 ,  0.993185,  0.869397,
        0.608351,  0.25126 , -0.1455  ])
Coordinates:
    z        int64 0
  * x        (x) float64 0.0 0.4 0.8 1.2 1.6 2.0 2.4 2.8 3.2 3.6 4.0 4.4 4.8 ...

In [31]:
arr.coords['x'].values

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8,
       5.2, 5.6, 6. , 6.4, 6.8, 7.2, 7.6, 8. ])

In [57]:
for k, v in arr.coords.items():
    print(k, v)

z <xarray.DataArray 'z' ()>
array(0, dtype=int64)
Coordinates:
    z        int64 0
x <xarray.DataArray 'x' (x: 21)>
array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2,
       5.6, 6. , 6.4, 6.8, 7.2, 7.6, 8. ])
Coordinates:
    z        int64 0
  * x        (x) float64 0.0 0.4 0.8 1.2 1.6 2.0 2.4 2.8 3.2 3.6 4.0 4.4 4.8 ...


In [60]:
v.values

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8,
       5.2, 5.6, 6. , 6.4, 6.8, 7.2, 7.6, 8. ])

In [62]:
arr.shape

(21,)

In [63]:
arr.coords['z']

<xarray.DataArray 'z' ()>
array(0, dtype=int64)
Coordinates:
    z        int64 0