In [2]:
%matplotlib notebook

In [3]:
import time
import numpy as np
import pandas as pd
import xarray as xr

from collections import OrderedDict
from importlib import reload

In [5]:
from plottr import plottr
reload(plottr)

<module 'plottr.plottr' from 'C:\\Users\\wopfa\\OneDrive - Microsoft\\Code\\plottr\\plottr\\plottr.py'>

In [14]:
def makeDatasetDictSimple(**kwargs):
    """
    convert specified numpy arrays into a dataset dictionary.
    first array is assumed to be data, all others axes (in given order).
    """
    names = [ k for k in kwargs.keys() ]
    dataset = {}
    for i, n in enumerate(names):
        dataset[n] = {}
        if isinstance(kwargs[n], np.ndarray):
            dataset[n]['values'] = kwargs[n].reshape(-1).tolist()
        else:
            dataset[n]['values'] = kwargs[n]
        if not i:
            dataset[n]['axes'] = names[1:]
            
    return dataset

# Combining data

In [20]:
xvals1 = []
yvals1 = []
zvals1 = []

xvals2 = []
yvals2 = []
zvals2 = []

for x in np.arange(4):
    for y in np.arange(3):
        if x < 2 and y < 2:
            xvals1.append(x)
            yvals1.append(y)
            zvals1.append(x+y)
        else:
            xvals2.append(x)
            yvals2.append(y)
            zvals2.append(x+y)
            
dict1 = makeDatasetDictSimple(z=zvals1, x=xvals1, y=yvals1)
df1 = plottr.dictToDataFrames(dict1)[0]

dict2 = makeDatasetDictSimple(z=zvals2, x=xvals2, y=yvals2)
df2 = plottr.dictToDataFrames(dict2)[0]

df = plottr.combineDataFrames(df1, df2)
df

z    0
x y   
0 0  0
  1  1
  2  2
1 0  1
  1  2
  2  3
2 0  2
  1  3
  2  4
3 0  3
  1  4
  2  5

In [7]:
dfs = plottr.dictToDataFrames(data['datasets'])
dfs

[z           0
 x            
 0.0  1.000000
 0.4  0.921061
 0.8  0.696707
 1.2  0.362358
 1.6 -0.029200
 2.0 -0.416147
 2.4 -0.737394
 2.8 -0.942222
 3.2 -0.998295
 3.6 -0.896758
 4.0 -0.653644
 4.4 -0.307333
 4.8  0.087499
 5.2  0.468517
 5.6  0.775566
 6.0  0.960170
 6.4  0.993185
 6.8  0.869397
 7.2  0.608351
 7.6  0.251260
 8.0 -0.145500]

In [81]:
for k, v in arr0.coords.items():
    if not isinstance(v.values, np.ndarray):
        arr0 = arr0.drop(k)

In [82]:
arr0

<xarray.DataArray (x: 21)>
array([ 1.      ,  0.921061,  0.696707,  0.362358, -0.0292  , -0.416147,
       -0.737394, -0.942222, -0.998295, -0.896758, -0.653644, -0.307333,
        0.087499,  0.468517,  0.775566,  0.96017 ,  0.993185,  0.869397,
        0.608351,  0.25126 , -0.1455  ])
Coordinates:
  * x        (x) float64 0.0 0.4 0.8 1.2 1.6 2.0 2.4 2.8 3.2 3.6 4.0 4.4 4.8 ...

TypeError: '<' not supported between instances of 'str' and 'int'

In [67]:
arr = plottr.dataFrameToXArray(dfs[0])
arr

<xarray.DataArray (x: 21)>
array([ 1.      ,  0.921061,  0.696707,  0.362358, -0.0292  , -0.416147,
       -0.737394, -0.942222, -0.998295, -0.896758, -0.653644, -0.307333,
        0.087499,  0.468517,  0.775566,  0.96017 ,  0.993185,  0.869397,
        0.608351,  0.25126 , -0.1455  ])
Coordinates:
    z        int64 0
  * x        (x) float64 0.0 0.4 0.8 1.2 1.6 2.0 2.4 2.8 3.2 3.6 4.0 4.4 4.8 ...

In [31]:
arr.coords['x'].values

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8,
       5.2, 5.6, 6. , 6.4, 6.8, 7.2, 7.6, 8. ])

In [57]:
for k, v in arr.coords.items():
    print(k, v)

z <xarray.DataArray 'z' ()>
array(0, dtype=int64)
Coordinates:
    z        int64 0
x <xarray.DataArray 'x' (x: 21)>
array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2,
       5.6, 6. , 6.4, 6.8, 7.2, 7.6, 8. ])
Coordinates:
    z        int64 0
  * x        (x) float64 0.0 0.4 0.8 1.2 1.6 2.0 2.4 2.8 3.2 3.6 4.0 4.4 4.8 ...


In [60]:
v.values

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8,
       5.2, 5.6, 6. , 6.4, 6.8, 7.2, 7.6, 8. ])

In [62]:
arr.shape

(21,)

In [63]:
arr.coords['z']

<xarray.DataArray 'z' ()>
array(0, dtype=int64)
Coordinates:
    z        int64 0